server:
  port: 9099

gin:
  application:
    name: "gin_rest_client"
  consul:
    host: localhost
    port: 8500


service:
  api:
    base-path: /services/gin-rest-client
    swagger-path: /swagger/gin-rest-client-docs/v3/api-docs/doc.json
    swagger-title: "gin rest client"
    swagger-version: "version1.1.0-1401/01/13"

  person-client:
    url: https://localhost
    port: 9090
    baseUrl : /services/person
    findAll: /findAll
    findByNationalCode: /find
    addPerson: /add
    updatePerson: /update
    deletePerson: /delete
    connection:
      readTimeout: 30000
      connecTionDuration: 30000
      connectTimeout: 10000
      connectionPerHost: 3000
    authorization:
      username : 'saber66'
      password: 'saber@123'


