basePath: /service/gin-rest-client
definitions:
  dto.AddPersonResponseDto:
    properties:
      error:
        $ref: '#/definitions/dto.ErrorResponse'
      response:
        $ref: '#/definitions/dto.Person'
    type: object
  dto.DeletePersonResponse:
    properties:
      code:
        type: integer
      text:
        type: string
    type: object
  dto.DeletePersonResponseDto:
    properties:
      error:
        $ref: '#/definitions/dto.ErrorResponse'
      response:
        $ref: '#/definitions/dto.DeletePersonResponse'
    type: object
  dto.ErrorResponse:
    properties:
      code:
        type: integer
      message:
        type: string
      originalMessage: {}
      validations:
        items:
          $ref: '#/definitions/dto.ValidationDto'
        type: array
    type: object
  dto.FindAllPersonResponse:
    properties:
      error:
        $ref: '#/definitions/dto.ErrorResponse'
      persons:
        items:
          $ref: '#/definitions/dto.Person'
        type: array
    type: object
  dto.FindPersonByNationalCodeResponseDto:
    properties:
      error:
        $ref: '#/definitions/dto.ErrorResponse'
        description: "null"
      response:
        $ref: '#/definitions/dto.Person'
    type: object
  dto.Person:
    properties:
      age:
        type: integer
      email:
        type: string
      firstname:
        type: string
      id:
        type: integer
      lastname:
        type: string
      mobile:
        type: string
      nationalCode:
        type: string
    type: object
  dto.PersonDto:
    properties:
      age:
        example: 35
        type: integer
      email:
        example: saberazizi66@yahoo.com
        type: string
      firstname:
        example: saber
        type: string
      lastname:
        example: azizi
        type: string
      mobile:
        example: "09365627895"
        type: string
      nationalCode:
        example: "0079028748"
        maxLength: 10
        minLength: 10
        type: string
    required:
    - age
    - email
    - firstname
    - lastname
    - mobile
    - nationalCode
    type: object
  dto.UpdatePersonResponseDto:
    properties:
      error:
        $ref: '#/definitions/dto.ErrorResponse'
      response:
        $ref: '#/definitions/dto.Person'
    type: object
  dto.ValidationDto:
    properties:
      detailMessage:
        type: string
      fieldName:
        type: string
    type: object
host: localhost:9099
info:
  contact:
    email: saberazizi66@yahoo.com
    name: API Support
    url: http://www.swagger.io/support
  description: gin rest client
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: gin rest client
  version: 1.0.0-1401/01/13
paths:
  /person/add:
    post:
      consumes:
      - application/json
      description: add person.
      parameters:
      - description: person body
        in: body
        name: personDto
        required: true
        schema:
          $ref: '#/definitions/dto.PersonDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.AddPersonResponseDto'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "406":
          description: Not Acceptable
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "504":
          description: Gateway Timeout
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: add person
      tags:
      - gin rest client
  /person/delete/{nationalCode}:
    delete:
      consumes:
      - application/json
      description: deletePersonByNationalCode
      parameters:
      - description: nationalCode param
        in: path
        name: nationalCode
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.DeletePersonResponseDto'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "406":
          description: Not Acceptable
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "504":
          description: Gateway Timeout
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: deletePersonByNationalCode
      tags:
      - gin rest client
  /person/find/{nationalCode}:
    get:
      consumes:
      - application/json
      description: findPersonByNationalCode
      parameters:
      - description: nationalCode param
        in: path
        name: nationalCode
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.FindPersonByNationalCodeResponseDto'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "406":
          description: Not Acceptable
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "504":
          description: Gateway Timeout
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: findPersonByNationalCode
      tags:
      - gin rest client
  /person/findAll:
    get:
      consumes:
      - application/json
      description: findAllPerson
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.FindAllPersonResponse'
      security:
      - ApiKeyAuth: []
      summary: findAllPerson
      tags:
      - gin rest client
  /person/update/{nationalCode}:
    put:
      consumes:
      - application/json
      description: update person by nationalCode.
      parameters:
      - description: nationalCode param
        in: path
        name: nationalCode
        required: true
        type: string
      - description: person body
        in: body
        name: personDto
        required: true
        schema:
          $ref: '#/definitions/dto.PersonDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UpdatePersonResponseDto'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "406":
          description: Not Acceptable
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "504":
          description: Gateway Timeout
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: update person by nationalCode
      tags:
      - gin rest client
schemes:
- http
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
